# .github/workflows/ci.yml
name: Node CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Node.js (pnpm will be available)
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      # 3. Install pnpm globally
      - run: corepack enable && corepack prepare pnpm@latest --activate

      # 4. Install dependencies
      - run: pnpm install

      # 5. Build the project
      - run: pnpm build
